// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	rbacv1 "k8s.io/api/rbac/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiService) DeepCopyInto(out *ApiService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiService.
func (in *ApiService) DeepCopy() *ApiService {
	if in == nil {
		return nil
	}
	out := new(ApiService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApiService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiServiceList) DeepCopyInto(out *ApiServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApiService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiServiceList.
func (in *ApiServiceList) DeepCopy() *ApiServiceList {
	if in == nil {
		return nil
	}
	out := new(ApiServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApiServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiServiceSpec) DeepCopyInto(out *ApiServiceSpec) {
	*out = *in
	if in.TotalReplicas != nil {
		in, out := &in.TotalReplicas, &out.TotalReplicas
		*out = new(int32)
		**out = **in
	}
	in.DeploymentSpec.DeepCopyInto(&out.DeploymentSpec)
	in.ServiceSpec.DeepCopyInto(&out.ServiceSpec)
	in.PodAutoScalerSpec.DeepCopyInto(&out.PodAutoScalerSpec)
	in.RoleMetadata.DeepCopyInto(&out.RoleMetadata)
	if in.RoleRules != nil {
		in, out := &in.RoleRules, &out.RoleRules
		*out = make([]rbacv1.PolicyRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.RoleBindingMetadata.DeepCopyInto(&out.RoleBindingMetadata)
	if in.RoleBindingSubjects != nil {
		in, out := &in.RoleBindingSubjects, &out.RoleBindingSubjects
		*out = make([]rbacv1.Subject, len(*in))
		copy(*out, *in)
	}
	out.RoleBindingRoleRef = in.RoleBindingRoleRef
	in.ServiceAccountMeta.DeepCopyInto(&out.ServiceAccountMeta)
	in.VirtualServiceSpec.DeepCopyInto(&out.VirtualServiceSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiServiceSpec.
func (in *ApiServiceSpec) DeepCopy() *ApiServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ApiServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiServiceStatus) DeepCopyInto(out *ApiServiceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiServiceStatus.
func (in *ApiServiceStatus) DeepCopy() *ApiServiceStatus {
	if in == nil {
		return nil
	}
	out := new(ApiServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualServiceDestination) DeepCopyInto(out *VirtualServiceDestination) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualServiceDestination.
func (in *VirtualServiceDestination) DeepCopy() *VirtualServiceDestination {
	if in == nil {
		return nil
	}
	out := new(VirtualServiceDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualServiceHttpSpec) DeepCopyInto(out *VirtualServiceHttpSpec) {
	*out = *in
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = make([]VirtualServiceUri, len(*in))
		copy(*out, *in)
	}
	out.Rewrite = in.Rewrite
	if in.Route != nil {
		in, out := &in.Route, &out.Route
		*out = make([]VirtualServiceDestination, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualServiceHttpSpec.
func (in *VirtualServiceHttpSpec) DeepCopy() *VirtualServiceHttpSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualServiceHttpSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualServiceSpec) DeepCopyInto(out *VirtualServiceSpec) {
	*out = *in
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Gateways != nil {
		in, out := &in.Gateways, &out.Gateways
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Http != nil {
		in, out := &in.Http, &out.Http
		*out = make([]VirtualServiceHttpSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualServiceSpec.
func (in *VirtualServiceSpec) DeepCopy() *VirtualServiceSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualServiceUri) DeepCopyInto(out *VirtualServiceUri) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualServiceUri.
func (in *VirtualServiceUri) DeepCopy() *VirtualServiceUri {
	if in == nil {
		return nil
	}
	out := new(VirtualServiceUri)
	in.DeepCopyInto(out)
	return out
}
