# permissions for end users to view apiservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apiservice-viewer-role
rules:
- apiGroups:
  - multitenancy.metricsadvisor.ai
  resources:
  - apiservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - multitenancy.metricsadvisor.ai
  resources:
  - apiservices/status
  verbs:
  - get
